# KJ: This is the environment used for training the graph_nets sc2fc model on AWS
# checkpoints saved on AWS work on osx-arm64 with this environment
name: tf2aws
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.9.17
    - numpy=1.23.5
    - scipy=1.10.1
    - tensorflow=2.12.0
    - tqdm
    - pip=22.0.4
    - pip:
        - dm-sonnet==2.0.1
        - dm-tree==0.1.8
        - future==0.18.3
        - matplotlib==3.5.3
        - networkx==3.1
        - pandas==2.0.3
        - scikit-learn==1.3.0
        - tabulate==0.9.0
        - tensorflow-probability==0.21.0
